title: Aibar Kamashev

description: Expert in reservoir simulation with Advanced Analytics and Programming skills, Data Science & Machine Learning & Databases knowledge and strong Mathematical background

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: youremail@gmail.com # Allow visitors to contact you
