title: Aibar Kamashev

description: Data Science and Reservoir Simulation Engineering

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: aibar.kamashev@gmail.com
